// Auto-generated by parallel_unsplash_photos_search
// Do not edit manually

export const IMAGES = {
  SOCIAL_HERO_1: "https://images.unsplash.com/photo-1502949298791-393048291bb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw0fHxzb2NpYWwlMjBtZWRpYSUyMGludGVyZmFjZXxlbnwwfDB8fHwxNzcwMjY5NzI0fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SOCIAL_HERO_10: "https://images.unsplash.com/photo-1762330462311-f75969906e16?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw5fHxzb2NpYWwlMjBtZWRpYSUyMGludGVyZmFjZXxlbnwwfDB8fHwxNzcwMjY5NzI0fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SOCIAL_HERO_2: "https://images.unsplash.com/photo-1498926506265-166e25d0910a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwzfHxzb2NpYWwlMjBtZWRpYSUyMGludGVyZmFjZXxlbnwwfDB8fHwxNzcwMjY5NzI0fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SOCIAL_HERO_3: "https://images.unsplash.com/photo-1710870509663-16f20f75d758?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwxfHxzb2NpYWwlMjBtZWRpYSUyMGludGVyZmFjZXxlbnwwfDB8fHwxNzcwMjY5NzI0fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SOCIAL_HERO_4: "https://images.unsplash.com/photo-1694878981750-3b1f8d97abff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw3fHxzb2NpYWwlMjBtZWRpYSUyMGludGVyZmFjZXxlbnwwfDB8fHwxNzcwMjY5NzI0fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SOCIAL_HERO_5: "https://images.unsplash.com/photo-1694878982007-0c361cc37960?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw4fHxzb2NpYWwlMjBtZWRpYSUyMGludGVyZmFjZXxlbnwwfDB8fHwxNzcwMjY5NzI0fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SOCIAL_HERO_6: "https://images.unsplash.com/photo-1694878981819-1084b2d7dd0b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwxMHx8c29jaWFsJTIwbWVkaWElMjBpbnRlcmZhY2V8ZW58MHwwfHx8MTc3MDI2OTcyNHww&ixlib=rb-4.1.0&q=80&w=1080",
  SOCIAL_HERO_7: "https://images.unsplash.com/photo-1651804805680-3565ef7807f6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwyfHxzb2NpYWwlMjBtZWRpYSUyMGludGVyZmFjZXxlbnwwfDB8fHwxNzcwMjY5NzI0fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SOCIAL_HERO_8: "https://images.unsplash.com/photo-1762330472091-73cd999f8ec7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw1fHxzb2NpYWwlMjBtZWRpYSUyMGludGVyZmFjZXxlbnwwfDB8fHwxNzcwMjY5NzI0fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SOCIAL_HERO_9: "https://images.unsplash.com/photo-1762340278788-66cc561ec06f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw2fHxzb2NpYWwlMjBtZWRpYSUyMGludGVyZmFjZXxlbnwwfDB8fHwxNzcwMjY5NzI0fDA&ixlib=rb-4.1.0&q=80&w=1080",
  TECH_BG_1: "https://images.unsplash.com/photo-1568952433726-3896e3881c65?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHwyfHx0ZWNobm9sb2d5JTIwbmV0d29ya3xlbnwwfDB8fHwxNzcwMjY5NzI2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  TECH_BG_10: "https://images.unsplash.com/photo-1764053430604-d585d1f1dad6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHw5fHx0ZWNobm9sb2d5JTIwbmV0d29ya3xlbnwwfDB8fHwxNzcwMjY5NzI2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  TECH_BG_2: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHwzfHx0ZWNobm9sb2d5JTIwbmV0d29ya3xlbnwwfDB8fHwxNzcwMjY5NzI2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  TECH_BG_3: "https://images.unsplash.com/photo-1644088379091-d574269d422f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHwxfHx0ZWNobm9sb2d5JTIwbmV0d29ya3xlbnwwfDB8fHwxNzcwMjY5NzI2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  TECH_BG_4: "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHw4fHx0ZWNobm9sb2d5JTIwbmV0d29ya3xlbnwwfDB8fHwxNzcwMjY5NzI2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  TECH_BG_5: "https://images.unsplash.com/photo-1667984550708-a6beba23cb4c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHw2fHx0ZWNobm9sb2d5JTIwbmV0d29ya3xlbnwwfDB8fHwxNzcwMjY5NzI2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  TECH_BG_6: "https://images.unsplash.com/photo-1645839078449-124db8a049fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHw0fHx0ZWNobm9sb2d5JTIwbmV0d29ya3xlbnwwfDB8fHwxNzcwMjY5NzI2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  TECH_BG_7: "https://images.unsplash.com/photo-1667984550873-c48666475fbb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHw3fHx0ZWNobm9sb2d5JTIwbmV0d29ya3xlbnwwfDB8fHwxNzcwMjY5NzI2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  TECH_BG_8: "https://images.unsplash.com/photo-1667984550719-1c44d1d07ed7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHw1fHx0ZWNobm9sb2d5JTIwbmV0d29ya3xlbnwwfDB8fHwxNzcwMjY5NzI2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  TECH_BG_9: "https://images.unsplash.com/photo-1636703781898-ff42a39ff202?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHwxMHx8dGVjaG5vbG9neSUyMG5ldHdvcmt8ZW58MHwwfHx8MTc3MDI2OTcyNnww&ixlib=rb-4.1.0&q=80&w=1080",
  USER_AVATAR_1: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwxfHxwcm9maWxlJTIwYXZhdGFyfGVufDB8Mnx8fDE3NzAyNjk3MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  USER_AVATAR_10: "https://images.unsplash.com/photo-1663255718476-a8176b4c460d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw4fHxwcm9maWxlJTIwYXZhdGFyfGVufDB8Mnx8fDE3NzAyNjk3MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  USER_AVATAR_2: "https://images.unsplash.com/photo-1545238377-dee9b7db2414?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw2fHxwcm9maWxlJTIwYXZhdGFyfGVufDB8Mnx8fDE3NzAyNjk3MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  USER_AVATAR_3: "https://images.unsplash.com/photo-1661265117335-4f2bb4cd966e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwxMHx8cHJvZmlsZSUyMGF2YXRhcnxlbnwwfDJ8fHwxNzcwMjY5NzI0fDA&ixlib=rb-4.1.0&q=80&w=1080",
  USER_AVATAR_4: "https://images.unsplash.com/photo-1628157588553-5eeea00af15c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwyfHxwcm9maWxlJTIwYXZhdGFyfGVufDB8Mnx8fDE3NzAyNjk3MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  USER_AVATAR_5: "https://images.unsplash.com/photo-1640960543409-dbe56ccc30e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwzfHxwcm9maWxlJTIwYXZhdGFyfGVufDB8Mnx8fDE3NzAyNjk3MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  USER_AVATAR_6: "https://images.unsplash.com/photo-1713330480270-4d4bee94f7b1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw3fHxwcm9maWxlJTIwYXZhdGFyfGVufDB8Mnx8fDE3NzAyNjk3MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  USER_AVATAR_7: "https://images.unsplash.com/photo-1654110455429-cf322b40a906?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw0fHxwcm9maWxlJTIwYXZhdGFyfGVufDB8Mnx8fDE3NzAyNjk3MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  USER_AVATAR_8: "https://images.unsplash.com/photo-1740252117070-7aa2955b25f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw5fHxwcm9maWxlJTIwYXZhdGFyfGVufDB8Mnx8fDE3NzAyNjk3MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  USER_AVATAR_9: "https://images.unsplash.com/photo-1595918161454-1abc7fdeaf4d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw1fHxwcm9maWxlJTIwYXZhdGFyfGVufDB8Mnx8fDE3NzAyNjk3MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
} as const;

export type ImageKey = keyof typeof IMAGES;
